### ISSUE TITLE
The check hangs forever

### ISSUE THREAD

**Issue by sindresorhus** [bconnorwhite/is-name-taken#1]
See: https://github.com/sindresorhus/npm-name-cli/issues/30 and https://github.com/sindresorhus/np/issues/592

**Comment by bconnorwhite** [comment]
Unfortunately NPM's syncing API has become super unreliable, so re-syncing packages on the fly probably doesn't make sense anymore.

My recommendation would be to use the `optimistic` flag, which prevents syncing. Instead, packages are compared against a local copy of all package names, which is [generated daily](https://github.com/bconnorwhite/all-package-names).
